# Generated by Django 5.1.7 on 2025-03-29 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0002_alter_bank_name_delete_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('ifsc', models.CharField(max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='banks.bank')),
            ],
        ),
    ]
